"""Report output formatting — table, CSV, JSON, and PDF renderers.

Renders an :class:`~secrets_audit.models.AuditReport` into one of four
formats: human-readable table (modeled on AWS CLI ``--output table``),
JSON, CSV, or PDF.

**Security invariant**: rendered output never contains secret values,
full IAM policy JSON, raw STS credentials, or session tokens.  The
``allowed_actions`` list is intentionally omitted from structured output
to avoid leaking policy details — only the derived ``access_level``
string is included.
"""

from __future__ import annotations

import csv
import io
import json
import logging
from datetime import datetime

from secrets_audit.models import (
    AuditReport,
    ICGroupResolution,
    IdentityCenterResolution,
    PrincipalAccess,
    PrincipalClassification,
)

logger = logging.getLogger(__name__)

# Maximum group members shown in table format before truncation
_TABLE_GROUP_MEMBER_LIMIT = 50


def render(report: AuditReport, output_format: str) -> str | bytes:
    """Dispatch to the appropriate renderer.

    Parameters
    ----------
    report:
        The fully-enriched audit report.
    output_format:
        One of ``"table"``, ``"json"``, ``"csv"``, or ``"pdf"``.

    Returns
    -------
    str | bytes
        The rendered report string (or bytes for PDF).

    Raises
    ------
    ValueError
        If *output_format* is not recognised.
    """
    dispatch: dict[str, object] = {
        "table": render_table,
        "json": render_json,
        "csv": render_csv,
        "pdf": render_pdf,
    }
    renderer = dispatch.get(output_format)
    if renderer is None:
        raise ValueError(f"Unknown output format: {output_format!r}")
    return renderer(report)


def render_table(report: AuditReport) -> str:
    """Render human-readable table with metadata header and columnar data.

    Columns: PRINCIPAL TYPE, PRINCIPAL NAME, IC USER / GROUP,
    ACCESS LEVEL, LAST ACCESSED.

    Group members are truncated at 50 in table format with
    ``"...and N more members"``.
    """
    lines: list[str] = []

    # --- Metadata header ---
    m = report.metadata
    lines.append(f"Secret: {m.secret_name}")
    lines.append(f"ARN:    {m.secret_arn}")
    lines.append(f"Region: {m.region if m.region is not None else '(default)'}")
    lines.append(f"Report generated: {m.generated_at}")
    lines.append(f"Generated by:     {m.generated_by}")
    lines.append(f"Tool:             {m.tool_version}")
    lines.append("")

    # --- Warnings ---
    for warning in report.warnings:
        lines.append(f"WARNING: {warning}")
    if report.warnings:
        lines.append("")

    # --- Empty principals ---
    if not report.principals:
        lines.append("No IAM principals have access to this secret")
        _append_versions_section(lines, report)
        return "\n".join(lines)

    # --- Column definitions ---
    headers = [
        "PRINCIPAL TYPE",
        "PRINCIPAL NAME",
        "IC USER / GROUP",
        "ACCESS LEVEL",
        "LAST ACCESSED",
    ]

    # Build rows — each principal produces one or more display rows.
    all_rows: list[list[str]] = []
    for p in report.principals:
        primary = _table_row(p)
        continuation = _ic_continuation_rows(p)
        all_rows.append(primary)
        all_rows.extend(continuation)

    # Calculate column widths
    widths = [len(h) for h in headers]
    for row in all_rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))

    # Format header line
    header_line = "   ".join(h.ljust(widths[i]) for i, h in enumerate(headers))
    separator = "   ".join("-" * widths[i] for i in range(len(headers)))
    lines.append(header_line)
    lines.append(separator)

    # Format data rows
    for row in all_rows:
        line = "   ".join(row[i].ljust(widths[i]) for i in range(len(headers)))
        lines.append(line)

    # --- Secret versions section ---
    _append_versions_section(lines, report)

    return "\n".join(lines)


def _table_row(p: PrincipalAccess) -> list[str]:
    """Build a single table row for a principal."""
    principal_type = p.principal_type.value
    principal_name = p.principal_name
    ic_col = _ic_column_table(p)
    access_level = p.access_level.value
    last_accessed = _format_last_accessed(p.last_accessed)
    return [principal_type, principal_name, ic_col, access_level, last_accessed]


def _ic_column_table(p: PrincipalAccess) -> str:
    """Derive the IC USER / GROUP column value for table output.

    Returns only the primary line. Group member details are rendered as
    continuation rows by :func:`_ic_continuation_rows`.
    """
    if p.classification == PrincipalClassification.EKS_SERVICE_ACCOUNT:
        return "Service Account (EKS)"

    if p.ic_resolution is None:
        return "N/A"

    ic = p.ic_resolution

    # If partial (cross-account failed), show permission set name only
    if ic.partial:
        return f"PS: {ic.permission_set_name}"

    parts: list[str] = []

    # Direct users
    for user in ic.users:
        if user.via_group is None:
            name = user.email or user.display_name or user.user_id
            parts.append(name)

    # Groups (name only — members shown as continuation rows)
    for group in ic.groups:
        parts.append(f"Group: {group.group_name}")

    # Group-based users (direct users assigned via group)
    for user in ic.users:
        if user.via_group is not None:
            name = user.email or user.display_name or user.user_id
            parts.append(f"{name} (via group {user.via_group})")

    if not parts:
        return f"PS: {ic.permission_set_name}"

    return ", ".join(parts)


def _ic_continuation_rows(p: PrincipalAccess) -> list[list[str]]:
    """Build continuation rows for group members in table output."""
    if p.ic_resolution is None or p.ic_resolution.partial:
        return []

    ic = p.ic_resolution
    rows: list[list[str]] = []

    for group in ic.groups:
        shown = group.members[:_TABLE_GROUP_MEMBER_LIMIT]
        for member in shown:
            name = member.email or member.display_name or member.user_id
            status = "Deleted" if member.deleted else "Enabled"
            rows.append(["", "", f"  {name} ({status})", "", ""])

        remaining = group.total_member_count - _TABLE_GROUP_MEMBER_LIMIT
        if remaining > 0:
            rows.append(["", "", f"...and {remaining} more members", "", ""])

    return rows


def _format_group_members_table(group: ICGroupResolution) -> list[str]:
    """Format group members for table output, truncating at 50."""
    if not group.members:
        return []

    shown = group.members[:_TABLE_GROUP_MEMBER_LIMIT]
    parts = [m.display_name or m.user_id for m in shown]

    remaining = group.total_member_count - _TABLE_GROUP_MEMBER_LIMIT
    if remaining > 0:
        parts.append(f"...and {remaining} more members")

    return parts


def _format_last_accessed(value: datetime | str | None) -> str:
    """Format the last_accessed field for display."""
    if value is None:
        return "N/A"
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M UTC")
    return str(value)


def _append_versions_section(lines: list[str], report: AuditReport) -> None:
    """Append the SECRET VERSIONS table section if versions are present."""
    if not report.versions:
        return

    lines.append("")
    lines.append("SECRET VERSIONS")
    v_headers = ["VERSION ID", "STAGING LABELS", "CREATED DATE"]
    v_rows: list[list[str]] = []
    for v in report.versions:
        labels = ", ".join(v.staging_labels)
        date_str = _format_last_accessed(v.created_date)
        v_rows.append([v.version_id, labels, date_str])

    v_widths = [len(h) for h in v_headers]
    for vr in v_rows:
        for i, cell in enumerate(vr):
            v_widths[i] = max(v_widths[i], len(cell))

    v_header_line = "   ".join(h.ljust(v_widths[i]) for i, h in enumerate(v_headers))
    v_separator = "   ".join("-" * v_widths[i] for i in range(len(v_headers)))
    lines.append(v_header_line)
    lines.append(v_separator)
    for vr in v_rows:
        lines.append(
            "   ".join(vr[i].ljust(v_widths[i]) for i in range(len(v_headers)))
        )


# ---------------------------------------------------------------------------
# Structured output helpers
# ---------------------------------------------------------------------------


def _principal_to_dict(p: PrincipalAccess) -> dict:
    """Convert a PrincipalAccess to a serialisable dict for JSON.

    Intentionally omits ``allowed_actions`` to avoid leaking raw policy
    details.  Only the derived ``access_level`` is included.
    """
    d: dict = {
        "principal_type": p.principal_type.value,
        "principal_name": p.principal_name,
        "access_level": p.access_level.value,
        "last_accessed": _serialise_last_accessed(p.last_accessed),
        "policy_source": p.policy_source,
    }

    # Classification-specific fields
    if p.classification == PrincipalClassification.EKS_SERVICE_ACCOUNT:
        d["is_service_account"] = True
        d["service_account_detail"] = p.eks_detail
        d["identity_center_user"] = None
        d["identity_center_group"] = None
    elif p.ic_resolution is not None:
        d["is_service_account"] = False
        d["service_account_detail"] = None
        d.update(_ic_to_dict(p.ic_resolution))
    else:
        d["is_service_account"] = False
        d["service_account_detail"] = None
        d["identity_center_user"] = None
        d["identity_center_group"] = None

    return d


def _ic_to_dict(ic: IdentityCenterResolution) -> dict:
    """Convert IC resolution to dict fields for structured output.

    Unlike table format, structured output includes the full member list
    (no truncation).
    """
    users_list = []
    for u in ic.users:
        entry: dict = {
            "user_id": u.user_id,
            "display_name": u.display_name,
            "email": u.email,
            "deleted": u.deleted,
        }
        if u.via_group is not None:
            entry["via_group"] = u.via_group
        users_list.append(entry)

    groups_list = []
    for g in ic.groups:
        members = []
        for m in g.members:
            members.append({
                "user_id": m.user_id,
                "display_name": m.display_name,
                "email": m.email,
                "deleted": m.deleted,
            })
        groups_list.append({
            "group_id": g.group_id,
            "group_name": g.group_name,
            "total_member_count": g.total_member_count,
            "members": members,
        })

    return {
        "permission_set_name": ic.permission_set_name,
        "identity_center_user": users_list if users_list else None,
        "identity_center_group": groups_list if groups_list else None,
        "ic_partial": ic.partial,
    }


def _serialise_last_accessed(value: datetime | str | None) -> str | None:
    """Serialise last_accessed for structured output."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value)


def _report_to_dict(report: AuditReport) -> dict:
    """Convert the full report to a serialisable dict."""
    m = report.metadata
    return {
        "secret_name": m.secret_name,
        "secret_arn": m.secret_arn,
        "region": m.region,
        "generated_at": m.generated_at,
        "generated_by": m.generated_by,
        "tool_version": m.tool_version,
        "warnings": report.warnings if report.warnings else [],
        "principals": [_principal_to_dict(p) for p in report.principals],
        "versions": [
            {
                "version_id": v.version_id,
                "staging_labels": v.staging_labels,
                "created_date": _serialise_last_accessed(v.created_date),
            }
            for v in report.versions
        ],
    }


def render_json(report: AuditReport) -> str:
    """Render JSON with ``indent=2``.

    Full group member lists (no truncation).
    """
    data = _report_to_dict(report)
    return json.dumps(data, indent=2, default=str)


# ---------------------------------------------------------------------------
# CSV renderer
# ---------------------------------------------------------------------------


def render_csv(report: AuditReport) -> str:
    """Render CSV with metadata as comment lines and principal data rows.

    For IC group members (when expand-groups produced group data), adds
    continuation rows with ``IC Group`` as the principal type.
    """
    buf = io.StringIO()

    # Metadata as comment lines
    m = report.metadata
    buf.write(f"# Secret: {m.secret_name}\n")
    buf.write(f"# ARN: {m.secret_arn}\n")
    buf.write(f"# Region: {m.region or '(default)'}\n")
    buf.write(f"# Report generated: {m.generated_at}\n")
    buf.write(f"# Generated by: {m.generated_by}\n")
    buf.write(f"# Tool: {m.tool_version}\n")

    writer = csv.writer(buf)
    headers = [
        "Principal Type",
        "Principal Name",
        "IC User / Group",
        "Access Level",
        "Last Accessed",
    ]
    writer.writerow(headers)

    for p in report.principals:
        ic_col = _ic_column_table(p)
        writer.writerow([
            p.principal_type.value,
            p.principal_name,
            ic_col,
            p.access_level.value,
            _format_last_accessed(p.last_accessed),
        ])

        # IC group member continuation rows
        if p.ic_resolution and not p.ic_resolution.partial:
            for group in p.ic_resolution.groups:
                for member in group.members:
                    email = member.email or member.display_name or member.user_id
                    status = "DISABLED" if member.deleted else "ENABLED"
                    writer.writerow([
                        "IC Group",
                        group.group_name,
                        email,
                        status,
                        "",
                    ])

    return buf.getvalue()


# ---------------------------------------------------------------------------
# PDF renderer
# ---------------------------------------------------------------------------


def render_pdf(report: AuditReport) -> bytes:
    """Render a PDF report using ReportLab.

    Returns raw PDF bytes.  The layout mirrors the terminal table format
    but formatted for US Letter paper.
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter)
    styles = getSampleStyleSheet()
    elements: list = []

    def _esc(text: str) -> str:
        """Escape text for ReportLab Paragraph XML parser."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

    # --- Metadata header ---
    m = report.metadata
    for line in [
        f"<b>Secret:</b> {_esc(m.secret_name)}",
        f"<b>ARN:</b> {_esc(m.secret_arn)}",
        f"<b>Region:</b> {_esc(m.region or '(default)')}",
        f"<b>Report generated:</b> {_esc(m.generated_at)}",
        f"<b>Generated by:</b> {_esc(m.generated_by)}",
        f"<b>Tool:</b> {_esc(m.tool_version)}",
    ]:
        elements.append(Paragraph(line, styles["Normal"]))
    elements.append(Spacer(1, 12))

    # --- Warnings ---
    for warning in report.warnings:
        elements.append(Paragraph(f"<b>WARNING:</b> {_esc(warning)}", styles["Normal"]))
    if report.warnings:
        elements.append(Spacer(1, 12))

    # --- Principals table ---
    if not report.principals:
        elements.append(Paragraph("No IAM principals have access to this secret", styles["Normal"]))
    else:
        headers = [
            "Principal Type",
            "Principal Name",
            "IC User / Group",
            "Access Level",
            "Last Accessed",
        ]
        data = [headers]
        for p in report.principals:
            data.append([
                p.principal_type.value,
                p.principal_name,
                _ic_column_table(p),
                p.access_level.value,
                _format_last_accessed(p.last_accessed),
            ])

        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(table)

    # --- Versions table ---
    if report.versions:
        elements.append(Spacer(1, 12))
        elements.append(Paragraph("<b>Secret Versions</b>", styles["Heading3"]))
        v_headers = ["Version ID", "Staging Labels", "Created Date"]
        v_data = [v_headers]
        for v in report.versions:
            v_data.append([
                v.version_id,
                ", ".join(v.staging_labels),
                _format_last_accessed(v.created_date),
            ])
        v_table = Table(v_data, repeatRows=1)
        v_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ]))
        elements.append(v_table)

    doc.build(elements)
    return buf.getvalue()
